
import type { Metadata } from "next";
import "./globals.css";

import SmoothScroller from "./components/ui/SmoothScroller";
import { JetBrains_Mono } from "next/font/google";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

export const metadata: Metadata = {
  title: "Get Hyped",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={cn("font-mono", jetbrainsMono.variable)}>
      <SmoothScroller/>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
